name: Check formatting and types

on:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!source/_posts/archive/**'
      - '!scaffolds/**'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: Check
        run: |
          pnpm install
          pnpm run check
