name: Deploy static content to Tencent Cloud COS

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: cos
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install and setup coscli
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p "$RUNNER_TEMP/coscli"
          cd "$RUNNER_TEMP/coscli"
          gh release download --repo tencentyun/coscli --pattern '*-linux-amd64' --pattern sha256sum.log
          sha256sum --check --ignore-missing sha256sum.log
          mv coscli-*-linux-amd64 coscli
          chmod a+x coscli
          echo "$RUNNER_TEMP/coscli" >> "$GITHUB_PATH"
          ./coscli --version
          ./coscli config set --secret_id '${{ secrets.COS_SECRETID }}' --secret_key '${{ secrets.COS_SECRETKEY }}' --disable_auto_fetch_bucket_type true
          ./coscli config add -b '${{ secrets.COS_BUCKET }}' -r '${{ secrets.COS_REGION }}' -a site

      - name: Generate static content
        run: |
          pnpm install
          pnpm run build

      - name: Deploy to COS
        run: |
          coscli sync public/ cos://site/ -r --delete --force --skip-dir --routines 10
